// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEfHdne4344pyg0W5nb1-0mnobDZ_H0I',
    appId: '1:694633775834:web:0abebea5975b4655609be3',
    messagingSenderId: '694633775834',
    projectId: 'public-transport-tracker-52dd7',
    authDomain: 'public-transport-tracker-52dd7.firebaseapp.com',
    storageBucket: 'public-transport-tracker-52dd7.firebasestorage.app',
    measurementId: 'G-WS5475VZTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABs0pP_3uRSUqEDQf0RjphB6GR3mc9-00',
    appId: '1:694633775834:android:6510d1f7fb8400e9609be3',
    messagingSenderId: '694633775834',
    projectId: 'public-transport-tracker-52dd7',
    storageBucket: 'public-transport-tracker-52dd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDHMpzBtkxWAe7n5HqGSSfYtpUmyDsmQg',
    appId: '1:694633775834:ios:637b9805e4656cd0609be3',
    messagingSenderId: '694633775834',
    projectId: 'public-transport-tracker-52dd7',
    storageBucket: 'public-transport-tracker-52dd7.firebasestorage.app',
    iosBundleId: 'com.example.publicTransportTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDHMpzBtkxWAe7n5HqGSSfYtpUmyDsmQg',
    appId: '1:694633775834:ios:637b9805e4656cd0609be3',
    messagingSenderId: '694633775834',
    projectId: 'public-transport-tracker-52dd7',
    storageBucket: 'public-transport-tracker-52dd7.firebasestorage.app',
    iosBundleId: 'com.example.publicTransportTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLEfHdne4344pyg0W5nb1-0mnobDZ_H0I',
    appId: '1:694633775834:web:cc7380c9aec42dd1609be3',
    messagingSenderId: '694633775834',
    projectId: 'public-transport-tracker-52dd7',
    authDomain: 'public-transport-tracker-52dd7.firebaseapp.com',
    storageBucket: 'public-transport-tracker-52dd7.firebasestorage.app',
    measurementId: 'G-72ELH4VE0V',
  );
}
